defmodule Mix.Tasks.SootTelemetry.Install.Docs do
  @moduledoc false

  def short_doc do
    "Installs soot_telemetry resources, ClickHouse config, and migration scaffolding"
  end

  def example do
    "mix igniter.install soot_telemetry"
  end

  def long_doc do
    """
    #{short_doc()}

    Generates a `Telemetry` Ash domain plus the `Schema`, `Stream`, and
    `IngestSession` resource stubs in the operator's project, creates
    the `priv/migrations/clickhouse/` output directory used by
    `mix soot_telemetry.gen_migrations`, and wires a default
    `clickhouse_url` into the dev/test configs. Composed by
    `mix soot.install`; can also be run standalone.

    See the `UI-SPEC.md` in the `soot` package for the full design.

    ## Example

    ```bash
    #{example()}
    ```

    ## Options

      * `--example` — same shape as the rest of the Soot installers;
        currently a no-op for `soot_telemetry` (the generated stubs are
        already runnable). Reserved for future illustrative streams.
      * `--yes` — answer yes to dependency-fetching prompts.
    """
  end
end

if Code.ensure_loaded?(Igniter) do
  defmodule Mix.Tasks.SootTelemetry.Install do
    @shortdoc "#{__MODULE__.Docs.short_doc()}"
    @moduledoc __MODULE__.Docs.long_doc()

    use Igniter.Mix.Task

    @impl Igniter.Mix.Task
    def info(_argv, _composing_task) do
      %Igniter.Mix.Task.Info{
        group: :soot,
        example: __MODULE__.Docs.example(),
        only: nil,
        composes: [],
        schema: [example: :boolean, yes: :boolean],
        defaults: [example: false, yes: false],
        aliases: [y: :yes, e: :example]
      }
    end

    @impl Igniter.Mix.Task
    def igniter(igniter) do
      app = Igniter.Project.Application.app_name(igniter)
      telemetry_module = Igniter.Project.Module.module_name(igniter, "Telemetry")
      schema_module = Igniter.Project.Module.module_name(igniter, "Telemetry.Schema")
      stream_module = Igniter.Project.Module.module_name(igniter, "Telemetry.Stream")
      session_module = Igniter.Project.Module.module_name(igniter, "Telemetry.IngestSession")

      igniter
      |> Igniter.Project.Formatter.import_dep(:soot_telemetry)
      |> create_telemetry_domain(telemetry_module, [
        schema_module,
        stream_module,
        session_module
      ])
      |> create_resource_stub(schema_module, telemetry_module, "Schema")
      |> create_resource_stub(stream_module, telemetry_module, "Stream")
      |> create_resource_stub(session_module, telemetry_module, "IngestSession")
      |> create_clickhouse_migrations_dir(app)
      |> configure_clickhouse_url()
      |> note_next_steps()
    end

    defp create_telemetry_domain(igniter, module, resources) do
      resource_lines = Enum.map_join(resources, "\n", fn r -> "    resource #{inspect(r)}" end)

      Igniter.Project.Module.create_module(
        igniter,
        module,
        """
        @moduledoc \"\"\"
        Telemetry domain — owns Schema, Stream, and IngestSession
        resources for this operator's project.

        Generated stub. Operators can add their own resources, policies,
        and custom actions; the framework does not re-touch this file
        once generated.
        \"\"\"

        use Ash.Domain

        resources do
        #{resource_lines}
        end
        """
      )
    end

    defp create_resource_stub(igniter, module, domain, label) do
      Igniter.Project.Module.create_module(
        igniter,
        module,
        """
        @moduledoc \"\"\"
        #{label} resource stub generated by `mix soot_telemetry.install`.

        Extend with attributes, actions, and relationships as needed;
        the framework does not re-touch this file once generated.
        \"\"\"

        use Ash.Resource, domain: #{inspect(domain)}

        actions do
        end
        """
      )
    end

    defp create_clickhouse_migrations_dir(igniter, _app) do
      Igniter.create_new_file(
        igniter,
        "priv/migrations/clickhouse/.gitkeep",
        "",
        on_exists: :skip
      )
    end

    defp configure_clickhouse_url(igniter) do
      igniter
      |> Igniter.Project.Config.configure(
        "dev.exs",
        :soot_telemetry,
        [:clickhouse_url],
        "http://localhost:8123"
      )
      |> Igniter.Project.Config.configure(
        "test.exs",
        :soot_telemetry,
        [:clickhouse_url],
        "http://localhost:8123"
      )
    end

    defp note_next_steps(igniter) do
      Igniter.add_notice(igniter, """
      soot_telemetry installed.

      Generated:

        lib/<app>/telemetry.ex            Ash domain
        lib/<app>/telemetry/schema.ex     Schema resource stub
        lib/<app>/telemetry/stream.ex     Stream resource stub
        lib/<app>/telemetry/ingest_session.ex
        priv/migrations/clickhouse/       ClickHouse DDL output dir

      Next steps:

        mix soot_telemetry.gen_migrations   # render ClickHouse DDL
        # then apply the rendered .sql files against your cluster

      The `:soot_telemetry, :clickhouse_url` key has been seeded in
      `config/dev.exs` and `config/test.exs`. Override in
      `config/runtime.exs` for production.
      """)
    end
  end
else
  defmodule Mix.Tasks.SootTelemetry.Install do
    @shortdoc "#{__MODULE__.Docs.short_doc()} | Install `igniter` to use"
    @moduledoc __MODULE__.Docs.long_doc()

    use Mix.Task

    def run(_argv) do
      Mix.shell().error("""
      The task `soot_telemetry.install` requires igniter. Add
      `{:igniter, "~> 0.6"}` to your project deps and try again, or
      invoke via:

          mix igniter.install soot_telemetry

      For more information, see https://hexdocs.pm/igniter
      """)

      exit({:shutdown, 1})
    end
  end
end
