defmodule Mix.Tasks.SootTelemetry.GenMigrations do
  @shortdoc "Render ClickHouse CREATE TABLE statements for telemetry streams"

  @moduledoc """
  Render ClickHouse migration statements for one or more telemetry stream
  modules and write them to disk.

      mix soot_telemetry.gen_migrations \\
            --out priv/migrations/V0001__telemetry_streams.sql \\
            --stream MyApp.Telemetry.Vibration \\
            --stream MyApp.Telemetry.Power

  Pass `--stream` once per module. The output is a plain `.sql` file
  ready to feed `clickhouse-client < file.sql` or to apply via the
  operator's preferred migration runner.
  """

  use Mix.Task

  @switches [out: :string, stream: [:string, :keep], database: :string]

  @impl Mix.Task
  def run(args) do
    Mix.Task.run("app.start")
    {opts, _} = OptionParser.parse!(args, strict: @switches)

    out = Keyword.fetch!(opts, :out)
    streams = opts |> Keyword.get_values(:stream) |> Enum.map(&load_module/1)

    if streams == [] do
      Mix.raise("at least one --stream <module> is required")
    end

    File.mkdir_p!(Path.dirname(out))
    sql = SootTelemetry.ClickHouse.DDL.create_tables(streams, opts)

    body =
      "-- Generated by mix soot_telemetry.gen_migrations\n" <>
        "-- Streams: " <>
        Enum.map_join(streams, ", ", &inspect/1) <>
        "\n\n" <>
        sql <> "\n"

    File.write!(out, body)
    Mix.shell().info("wrote #{out}")
  end

  defp load_module(name) do
    mod = Module.concat([name])

    case Code.ensure_loaded(mod) do
      {:module, ^mod} -> mod
      {:error, reason} -> Mix.raise("could not load #{name} (#{inspect(reason)})")
    end
  end
end
