defmodule SootTelemetry.MixTasksTest do
  use ExUnit.Case, async: false

  @tmp Path.join(System.tmp_dir!(), "soot_telemetry_mix_tasks_test")

  setup do
    File.rm_rf!(@tmp)
    File.mkdir_p!(@tmp)
    on_exit(fn -> File.rm_rf!(@tmp) end)
    :ok
  end

  describe "mix soot_telemetry.gen_migrations" do
    test "writes a SQL file containing CREATE TABLE statements" do
      out = Path.join(@tmp, "0001.sql")

      Mix.Tasks.SootTelemetry.GenMigrations.run([
        "--out",
        out,
        "--stream",
        "SootTelemetry.Test.Fixtures.Vibration",
        "--stream",
        "SootTelemetry.Test.Fixtures.Power"
      ])

      body = File.read!(out)
      assert body =~ "Generated by mix soot_telemetry.gen_migrations"
      assert body =~ "CREATE TABLE IF NOT EXISTS telemetry_vibration"
      assert body =~ "CREATE TABLE IF NOT EXISTS telemetry_power"
    end

    test "errors out without --stream" do
      out = Path.join(@tmp, "x.sql")

      assert_raise Mix.Error, fn ->
        Mix.Tasks.SootTelemetry.GenMigrations.run(["--out", out])
      end
    end

    test "--database produces fully-qualified table names" do
      out = Path.join(@tmp, "with_db.sql")

      Mix.Tasks.SootTelemetry.GenMigrations.run([
        "--out",
        out,
        "--database",
        "iot",
        "--stream",
        "SootTelemetry.Test.Fixtures.Vibration"
      ])

      assert File.read!(out) =~ "iot.telemetry_vibration"
    end
  end
end
